name: Deploy By WebDAV
on:
  push:
    branches:
    - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Code
      uses: bxb100/action-upload-webdav@v1
      with:
        webdav_address: ${{secrets.WEBDAV_URL}}
        webdav_username: ${{secrets.WEBDAV_USERNAME}}
        webdav_password: ${{secrets.WEBDAV_PASSWORD}}
        webdav_upload_path: "/Website"
        files: "./**"
